### ISSUE TITLE
not working 😮😮

### ISSUE THREAD

**Issue by luisnquin** [ui-1/nlet#1]
```bash
$ py main.py
Traceback (most recent call last):
  File "/tmp/nlet/main.py", line 1, in <module>
    import aiohttp
ModuleNotFoundError: No module named 'aiohttp'
```

**Comment by ui-1** [comment]
oops, you're supposed to install the required packages first (notice how the error is about a module not being found) — run `pip install -r requirements.txt` in the repo's directory. The commit e0cbafa also adds this to the readme

**Comment by luisnquin** [comment]
yeap, that was the idea
